swagger: '2.0'
info:
  title: Fabric context
  description: fabric service
  version: 1.0.0
host: tms.vass.es
basePath: /api/fabric
tags:
  - name: Electronic commerce
schemes:
  - https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /fabric/context/startProcess:
    post:
      tags:
        - Fabric context
      summary: Start process.
      security:
        - Bearer: []
      operationId: startProcessFabric
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: session
          type: string
          description: session
          required: true
      responses:
        '204':
          description: Response successfull
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ApiError'
        '500':
          description: Server error
          schema:
            $ref: '#/definitions/ApiError'
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
definitions:
  ApiError:
    type: object
    properties:
      type:
        type: string
      title:
        type: string
      status:
        type: integer
        format: int32
      detail:
        type: string
      message:
        type: string
